CXX=g++-mingw
LD=g++-mingw
CFLAGS=-DSFML_STATIC -ggdb -Wall -Wextra -std=c++11 -I./include
LDFLAGS=-static -L./win/bin -L./win/lib -lsfml-graphics-s -lsfml-window-s -lsfml-system-s -lopengl32 -lfreetype -ljpeg -lwinmm -lgdi32

EXEC=ttt.exe
SOURCES=$(wildcard *.cpp)
OBJECTS=$(SOURCES:.cpp=.o)

.PHONY: clean all run

all: clean $(EXEC)

run: all
	./$(EXEC)

$(EXEC): $(OBJECTS)
	$(LD) $(OBJECTS) $(LDFLAGS) -o $(EXEC)

%.o: %.cpp
	$(CXX) -c $(CFLAGS) $< -o $@ 

clean:
	rm -rf $(EXEC) $(OBJECTS)
